Assignment 2: formula_parser.c File Reference
formula_parser.c File Reference
#include "formula_parser.h"
Functions
void parseFormula (const char *inputFile, const char *outputFile)
Parses the chemical formulas from the input file and writes the expanded format to the output file.
void countProtons (ELEMENT elements[], int numElements, const char *inputFile, const char *outputFile)
Counts the total number of protons in the chemical formulas from the input file and writes the result to the output file.
int parenthesesValidation (const char *inputFile)
Validates the parentheses in the chemical formulas from the input file.
Function Documentation
countProtons()
void countProtons (ELEMENT elements[], int numElements, const char * inputFile, const char * outputFile)
Counts the total number of protons in the chemical formulas from the input file and writes the result to the output file.
Parameters
elements An array of ELEMENT structs representing the periodic table elements.
numElements The total number of elements in the array.
inputFile The path to the input file containing chemical formulas.
outputFile The path to the output file where the proton count results will be written.
 {
     if (parenthesesValidation(inputFile) != 0)
     {
         return;
     } // Validate parentheses in input file; exit if invalid
     parseFormula(inputFile, "parsedOutput.txt"); // Parse the formula and write to temporary parsed output file
     FILE *parsedOutput = fopen("parsedOutput.txt", "r"); // Open parsed output file for reading
     FILE *output = fopen(outputFile, "w");               // Open output file for writing proton counts
     if (parsedOutput == NULL || output == NULL)
     { // Check if files opened successfully
         perror("Error opening files in countProtons");
         return;
     }
     char line[2048]; // Buffer to store each line of parsed output
     while (fgets(line, sizeof(line), parsedOutput) != NULL)
     {                                     // Read each line from parsed output
         line[strcspn(line, "\n")] = '\0'; // Remove newline character from line
         int count = 0;                    // Proton count for the current line
         char *element = strtok(line, " "); // Tokenize line by spaces to get each element
         while (element != NULL)
         {
             count += findAtomicNumber(element, elements, numElements); // Add atomic number to current count
             element = strtok(NULL, " ");                               // Get next element in the line
         }
         fprintf(output, "%d\n", count); // Write proton count for the line to output file
     }
     fclose(parsedOutput); // Close parsed output file
     fclose(output);       // Close final output file
 }
References findAtomicNumber(), parenthesesValidation(), and parseFormula().
Referenced by main().
parenthesesValidation()
int parenthesesValidation (const char * inputFile)
Validates the parentheses in the chemical formulas from the input file.
Parameters
inputFile The path to the input file containing chemical formulas.
Returns
int Returns the number of lines with invalid parentheses. 0 indicates all lines are valid.
 {
     FILE *input = fopen(inputFile, "r"); // Open input file for reading
     if (input == NULL)
     { // Check if file opened successfully
         perror("Error opening file in parenthesesValidation function");
         exit(EXIT_FAILURE);
     }
     int invalidLines = 0; // Counter for lines with unbalanced parentheses
     STACK *stack = NULL;
     initStack(&stack);  // Initialize the stack
     char line[512];     // Buffer to store each line from the file
     int lineNumber = 0; // Track line number
     while (fgets(line, sizeof(line), input) != NULL)
     { // Read each line from input
         lineNumber++;
         bool isValid = true; // Flag to track if parentheses in the line are balanced
         // Process each character in the line
         for (int i = 0; line[i] != '\0'; i++)
         {
             char c = line[i];
             if (c != '(' && c != ')')
             { // Skip non-parentheses characters
                 continue;
             }
             if (c == '(')
             {
                 char str[2] = {c, '\0'}; // Convert '(' to string for pushing
                 push(stack, str);        // Push '(' onto the stack
             }
             else if (c == ')')
             {
                 if (!isEmpty(stack))
                 { // Check if stack has matching '(' to pop
                     char dummy[2];
                     pop(stack, dummy); // Pop matching '(' from stack
                 }
                 else
                 {
                     isValid = false; // Mark as invalid if no matching '('
                     break;           // Stop further checks for this line
                 }
             }
         }
         if (!isValid || !isEmpty(stack))
         { // Check for unmatched '(' after the line is processed
             printf("Parentheses NOT balanced in line: %d\n", lineNumber);
             invalidLines++; // Increment counter for lines with invalid parentheses
         }
         // Reset the stack for the next line by popping all elements if any are left
         while (!isEmpty(stack))
         {
             char dummy[2];
             pop(stack, dummy);
         }
     }
     freeStack(stack);    // Free the stack memory
     fclose(input);       // Close the input file after processing
     return invalidLines; // Return the count of invalid lines
 }
References freeStack(), initStack(), isEmpty(), pop(), and push().
Referenced by countProtons(), main(), and parseFormula().
parseFormula()
void parseFormula (const char * inputFile, const char * outputFile)
Parses the chemical formulas from the input file and writes the expanded format to the output file.
Parameters
inputFile The path to the input file containing chemical formulas.
outputFile The path to the output file where the expanded formulas will be written.
 {
     if (parenthesesValidation(inputFile) != 0)
     {
         return;
     } // Validate parentheses in input file; exit if invalid
     FILE *input = fopen(inputFile, "r");   // Open input file for reading
     FILE *output = fopen(outputFile, "w"); // Open output file for writing
     if (input == NULL || output == NULL)
     { // Check if files opened successfully
         perror("Error opening files!");
         exit(EXIT_FAILURE);
     }
     char formula[256];                                     // Buffer to store each formula line
     while (fgets(formula, sizeof(formula), input) != NULL) // Read each formula line
     {
         formula[strcspn(formula, "\n")] = '\0'; // Remove newline from formula
         STACK *stack = NULL;
         initStack(&stack); // Initialize stack for parsing formula
         parseFormulaHelper(formula, stack); // Call the helper to parse each formula line
         // Reverse stack to correct order for output
         STACK *reversedStack = NULL;
         initStack(&reversedStack);
         while (!isEmpty(stack))
         {
             char *element = (char *)malloc(4 * sizeof(char)); // Dynamically allocate element buffer
             pop(stack, element);          // Pop from main stack
             push(reversedStack, element); // Push onto reversed stack
             free(element); // Free the dynamically allocated buffer
         }
         while (!isEmpty(reversedStack))
         { // Output elements in correct order
             char *element = (char *)malloc(4 * sizeof(char)); // Dynamically allocate element buffer
             pop(reversedStack, element);
             fprintf(output, "%s ", element); // Write element to output file
             free(element); // Free the dynamically allocated buffer
         }
         fprintf(output, "\n");
         freeStack(stack);         // Free main stack
         freeStack(reversedStack); // Free reversed stack
     }
     fclose(input);  // Close input file
     fclose(output); // Close output file
 }
References initStack(), and parenthesesValidation().
Referenced by countProtons(), and main().