Assignment 2: stack.h File Reference
stack.h File Reference
This file contains declarations for a stack data structure that stores strings and provides basic stack operations.
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Data Structures
struct node
Represents a node in the stack.
struct stack
Represents the stack structure.
Macros
#define MAX_SIZE 4
Define the maximum size of the string in a stack node.
Typedefs
typedef struct node NODE
Represents a node in the stack.
typedef struct stack STACK
Represents the stack structure.
Functions
int initStack (STACK **stack)
Initializes a new stack.
bool isEmpty (STACK *stack)
Checks if the stack is empty.
int top (STACK *stack, char *retValue)
Retrieves the top element of the stack without removing it.
int push (STACK *stack, const char *value)
Pushes a new element onto the stack.
int pop (STACK *stack, char *retValue)
Removes the top element from the stack and retrieves its value.
void printStack (STACK *stack)
Prints the entire stack to the console.
void freeStack (STACK *stack)
Frees all memory allocated for the stack.
Detailed Description
This file contains declarations for a stack data structure that stores strings and provides basic stack operations.
Macro Definition Documentation
MAX_SIZE
#define MAX_SIZE 4
Define the maximum size of the string in a stack node.
Typedef Documentation
NODE
typedef struct node NODE
Represents a node in the stack.
STACK
typedef struct stack STACK
Represents the stack structure.
Function Documentation
freeStack()
void freeStack (STACK * stack)
Frees all memory allocated for the stack.
Parameters
stack A pointer to the stack to be freed.
 {
     if (stack == NULL)
         return;
     while (!isEmpty(stack))
     {
         char temp[MAX_SIZE];
         pop(stack, temp); // Pop all elements to free nodes
     }
     free(stack); // Free the stack structure itself
 }
References isEmpty(), MAX_SIZE, and pop().
Referenced by parenthesesValidation().
initStack()
int initStack (STACK ** stack)
Initializes a new stack.
Parameters
stack A double pointer to the stack to be initialized.
Returns
int Returns 0 on success, or an error code on failure.
 {
     *stack = (STACK *)malloc(sizeof(STACK));
     if ((*stack) == NULL)
         return EXIT_FAILURE;
     (*stack)->top = NULL;
     (*stack)->size = 0;
     return EXIT_SUCCESS;
 }
References stack::top.
Referenced by parenthesesValidation(), and parseFormula().
isEmpty()
bool isEmpty (STACK * stack)
Checks if the stack is empty.
Parameters
stack A pointer to the stack.
Returns
bool Returns true if the stack is empty, false otherwise.
 {
     return stack->size == 0;
 }
References stack::size.
Referenced by freeStack(), parenthesesValidation(), pop(), and printStack().
pop()
int pop (STACK * stack, char * retValue)
Removes the top element from the stack and retrieves its value.
Parameters
stack A pointer to the stack.
retValue A buffer to store the popped element's value.
Returns
int Returns 0 on success, or an error code on failure.
 {
     if (stack == NULL || isEmpty(stack))
     {
         printf("Stack is empty!");
         return EXIT_FAILURE;
     }
     NODE *temp = stack->top;
     int length = strlen(temp->data);
     strncpy(retValue, temp->data, length);
     retValue[length] = '\0'; // Ensure null termination based on the actual string length
     stack->top = temp->next;
     stack->size--;
     free(temp); // Free the memory for the popped node
     return EXIT_SUCCESS;
 }
References node::data, isEmpty(), node::next, stack::size, and stack::top.
Referenced by freeStack(), and parenthesesValidation().
printStack()
void printStack (STACK * stack)
Prints the entire stack to the console.
Parameters
stack A pointer to the stack.
 {
     if (isEmpty(stack))
     {
         printf("Stack is empty!\n");
         return;
     }
     NODE *current = stack->top;
     printf("Stack elements (from top to bottom):\n");
     while (current != NULL)
     {
         printf("%s ", current->data);
         current = current->next;
     }
     printf("\n");
 }
References node::data, isEmpty(), node::next, and stack::top.
push()
int push (STACK * stack, const char * value)
Pushes a new element onto the stack.
Parameters
stack A pointer to the stack.
value The value to be pushed onto the stack.
Returns
int Returns 0 on success, or an error code on failure.
 {
     if (stack == NULL) {
         printf("Stack is not initialized\n");
         return EXIT_FAILURE;
     }
     NODE *newNode = (NODE *)malloc(sizeof(NODE));
     if (newNode == NULL)
     {
         printf("Cannot allocate space in stack");
         return EXIT_FAILURE;
     }
     // Copy the string value into the new node
     strncpy(newNode->data, value, strlen(value));
     newNode->data[strlen(value)] = '\0'; // Ensure null termination
     newNode->next = stack->top;
     stack->top = newNode;
     stack->size++;
     return EXIT_SUCCESS;
 }
References node::data, node::next, stack::size, and stack::top.
Referenced by parenthesesValidation().
top()
int top (STACK * stack, char * retValue)
Retrieves the top element of the stack without removing it.
Parameters
stack A pointer to the stack.
retValue A buffer to store the top element's value.
Returns
int Returns 0 on success, or an error code on failure.
 {
     if (stack == NULL || stack->top == NULL)
     {
         retValue[0] = '\0'; // Return an empty string if the stack is empty
         return EXIT_FAILURE;
     }
     strncpy(retValue, stack->top->data, strlen(stack->top->data));
     retValue[strlen(stack->top->data)] = '\0';
     return EXIT_SUCCESS;
 }
References node::data, and stack::top.